dt: 0.2

pnames:
  - Insp
  - Exp
  - Sw1
  - Sw2
  - Sensory_relay
  - KF_phasic
  - KF_gate

tau_m:
  Insp: 5000
  Exp: 5000
  Sw1: 1500
  Sw2: 1500
  Sensory_relay: 17500
  KF_phasic: 10000
  KF_gate: 5000

neuron_defaults:
  alpha: 1.0
  bias: -0.2
  tau_v: 0.5
  beta: 30.0

connections:
  "(Sw1, Sensory_relay)": 0.12
  "(Sw2, Sensory_relay)": 0.07
  "(Insp, Sensory_relay)": -0.4
  "(KF_phasic, Sensory_relay)": 0.03
  "(Sw2, Sw1)": -0.9
  "(Insp, Sw1)": -0.8
  "(Sw1, Sw2)": -0.65
  "(Exp, Insp)": -0.3
  "(Sw1, Insp)": -0.01
  "(KF_phasic, Insp)": -0.35
  "(Insp, Exp)": -0.7
  "(KF_phasic, Exp)": 0.03
  "(Exp, KF_phasic)": 0.03
  "(Sw1, KF_gate)": -0.15

drives_misc:
  "(Insp, CO2)": 0.3
  "(Sw1, wakefulness)": 0.19
  "(Sw2, wakefulness)": 0.35
  "(KF_gate, wakefulness)": 0.25
  "(Exp, pons)": 0.35
  "(KF_phasic, pons)": 0.35
  "(Insp, pons)": 0.05
